3.1.0 changes
fortinet-fortisoar/widget-ai-assistant pull request #19
Opened 2024-11-11 12:06 UTC by cs-abhishek-shukla

- Release notes updated

2024-11-22 06:49 UTC, cs-suyog-jinturkar commented on release_notes.md
> +> This feature is currently unsupported on the Firefox browser.
please add this note in the content/setup section as well.

2024-11-22 06:50 UTC, cs-suyog-jinturkar commented on release_notes.md
> +Try the Voice Recognition feature to elevate your SOC workflow!
Clear conversation option now doesn't delete the conversation thread from the openAI. more details can be provided by @cs-ankit-gupta

2024-11-22 06:51 UTC, cs-suyog-jinturkar commented on release_notes.md
> +Try the Voice Recognition feature to elevate your SOC workflow!
applicalbe in release notes as well in content/usage section

2024-11-22 09:57 UTC, cs-ankit-gupta requested changes

2024-11-22 09:57 UTC, cs-ankit-gupta commented on docs/usage.md
> +>Clearing a conversation deletes the conversation and starts a new thread. Hence generative AIs, like OpenAI, may lose context.
Now it does not delete a thread @cs-abhishek-shukla, we only clear the conversation

2024-11-22 09:57 UTC, cs-ankit-gupta commented on release_notes.md
> +**Enhanced AI Assistant with Voice Recognition Feature**
New release note as that now we are not deleting the thread from OpenAI, we are only clearing the conversation

2024-11-28 14:20 UTC, cs-rahul-vishwakarma requested changes

2024-11-28 14:20 UTC, cs-rahul-vishwakarma commented on docs/usage.md
> +1. Click to launch a relevant module for the bot icon to appear. For example, *Alerts*, *Incidents*, and *Playbooks* are some modules on which the bot icon appears.
"Playbooks" is not a module. Change it to "Indicators"

2024-12-05 09:59 UTC, merged